### ISSUE TITLE
Crash on 1.19.2

### ISSUE THREAD

**Issue by Sunconure11** [DaFuqs/SpectralDecorations#3]
https://gist.github.com/Sunconure11/057133c5bf0a499e3922e56cde02a0f6

@DaFuqs

**Comment by unilock** [comment]
I'm running into this issue on 1.20.1 as well.

I believe the issue is here:
https://github.com/DaFuqs/SpectralDecorations/blob/656ced40f5cc38cc14047667b2491d6b7c0787f8/src/main/java/de/dafuqs/spectral_decorations/SpectralDecorationsBlocks.java#L55

I'm guessing `ColoredLogBlock.byColor(dyeColor)` is returning `null` for some reason; maybe the `block` parameter of the surrounding method can be used directly instead? (assuming `.add()` is expecting a `Block`)

**Comment by Sunconure11** [comment]
@unilock The dev is working on a build that fixes this.
